# -*- coding: utf-8 -*-
"""ipmlab(CSI) 라벨링

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZRzvOIgjGttJK0F02aHbKtN3b2FrtmL7
"""

import pandas as pd

path3='/content/drive/MyDrive/ipm/labeling_file.xlsx'

label=pd.read_excel(path3,sheet_name='공사비_범위' , header=None)
label_dict = dict(zip(label.iloc[:, 0], label.iloc[:, 1]))

# 공사비 범위 변경

for key, value in final_result.items():
    if '공사비' in value:
        temp_value = value['공사비']
        final_result[key]['공사비'] = label_dict.get(temp_value, temp_value)

#공종(소분류), 공종(대분류) tuple dic 생성

def create_dict_from_excel(path3, sheet_name, key_column_count):
    data = pd.read_excel(path3, sheet_name=sheet_name, header=None)
    key_columns = data.iloc[:, :key_column_count]
    value_column = data.iloc[:, key_column_count]

    result_dict = {}
    for row in range(len(data)):
        key = tuple(key_columns.iloc[row])
        value = value_column.iloc[row]
        result_dict[key] = value

    return result_dict

sheet_names = ['공종(대분류)', '공종(소분류)']

label2_dict = {}
label3_dict = {}

for sheet_name in sheet_names:
    if sheet_name == '공종(대분류)':
        key_column_count = 2
        label2_dict = create_dict_from_excel(path3, sheet_name, key_column_count)
    elif sheet_name == '공종(소분류)':
        key_column_count = 3
        label3_dict = create_dict_from_excel(path3, sheet_name, key_column_count)
    else:
        continue

def labeling_dic(final_result):

    label_names = ['사고상태','공공민간구분','공사비','사고월', '사고요일', '사고시간','날씨','시설물 대분류','사고객체(대분류)','인적사고종류(대분류)','시도구분','공정율','작업자수','프로세스','안전관리계획','설계안정성검토']
    label_keys = ['사고상태','공공민간구분','공사비','사고월', '사고요일', '사고시간','날씨','시설물 대분류','사고객체(대분류)','인적사고종류(대분류)','시도구분','공정율','작업자수','프로세스','안전관리계획','설계안정성검토']
    label_num_keys = ['사고상태_num','공공민간구분-num','공사비_num','사고월_num', '사고요일_num', '사고시간_num','날씨_num','시설물 대분류_num','사고객체(대분류)_num','인적사고종류(대분류)_num','시도구분_num','공정율_num','작업자수_num','프로세스_num'
    ,'안전관리계획_num','설계안정성검토_num']

    label_dicts = [None] * len(label_names)

    for i, label_name in enumerate(label_names):
        label = pd.read_excel(path3, sheet_name=label_name, header=None)
        label_dict = dict(zip(label.iloc[:, 0], label.iloc[:, 1]))
        label_dicts[i] = label_dict

    for key, value in final_result.items():
        for i, label_key in enumerate(label_keys):
            if label_key in value:
                temp_value = value[label_key]
                final_result[key][label_num_keys[i]] = label_dicts[i].get(temp_value, temp_value)

    for main_key, sub_dict in final_result.items():
        subkey1_value = sub_dict.get('시설물대분류')
        subkey2_value = sub_dict.get('공종(대분류)')

        if (subkey1_value, subkey2_value) in label2_dict:
            new_value = label2_dict[(subkey1_value, subkey2_value)]
            final_result[main_key]['공종(대분류)_num'] = new_value

    for main_key, sub_dict in final_result.items():
        subkey1_value = sub_dict.get('시설물대분류')
        subkey2_value = sub_dict.get('공종(대분류)')
        subkey3_value = sub_dict.get('공종(소분류)')

        if (subkey1_value, subkey2_value, subkey3_value) in label3_dict:
            new_value = label3_dict[(subkey1_value, subkey2_value, subkey3_value)]
            final_result[main_key]['공종(소분류)_num'] = new_value

    return final_result

labeling_result = labeling_dic(final_result)