# -*- coding: utf-8 -*-
"""ipmlab(CSI) 라벨링

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZRzvOIgjGttJK0F02aHbKtN3b2FrtmL7
"""

path3='/content/drive/MyDrive/ipm/labeling_file.xlsx'

label=pd.read_excel(path3, header=None)
label_dict = dict(zip(label.iloc[:, 0], label.iloc[:, 1]))

# 공사비 범위 변경

for key, value in final_result.items():
    if '사고상태' in value:
        temp_value = value['사고상태']
        final_result[key]['사고상태'] = label_dict.get(temp_value, temp_value)

def labeling_dic(final_result):

    label_names = ['사고상태','공공민간구분','공사비','사고월', '사고요일', '사고시간','날씨','시설물 대분류','사고객체(대분류)','인적사고종류(대분류)','시도구분','공정율','작업자수','프로세스','안전관리계획','설계안정성검토']
    label_keys = ['사고상태','공공민간구분','공사비','사고월', '사고요일', '사고시간','날씨','시설물 대분류','사고객체(대분류)','인적사고종류(대분류)','시도구분','공정율','작업자수','프로세스','안전관리계획','설계안정성검토']
    label_num_keys = ['사고상태_num','공공민간구분-num','공사비_num','사고월_num', '사고요일_num', '사고시간_num','날씨_num','시설물 대분류_num','사고객체(대분류)_num','인적사고종류(대분류)_num','시도구분_num','공정율_num','작업자수_num','프로세스_num'
    ,'안전관리계획_num','설계안정성검토_num']

    label_dicts = [None] * len(label_names)

    for i, label_name in enumerate(label_names):
        label = pd.read_excel(path3, sheet_name=label_name, header=None)
        label_dict = dict(zip(label.iloc[:, 0], label.iloc[:, 1]))
        label_dicts[i] = label_dict

    for key, value in final_result.items():
        for i, label_key in enumerate(label_keys):
            if label_key in value:
                temp_value = value[label_key]
                final_result[key][label_num_keys[i]] = label_dicts[i].get(temp_value, temp_value)


   #공종(대분류)/ 공종(소분류)


    for key, value in final_result.items():
        if value['시설물대분류']=="토목" and value ['공종(대분류)']=="토목":
          value['공종(대분류)_num'] = 1100
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="건축":
          value['공종(대분류)_num'] = 1200
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="산업설비":
          value['공종(대분류)_num'] = 1310
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="기계설비":
          value['공종(대분류)_num'] = 1320
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="전기설비":
          value['공종(대분류)_num'] = 1330
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="통신설비":
          value['공종(대분류)_num'] = 1340
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="기타":
          value['공종(대분류)_num'] = 1900
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="토목":
          value['공종(대분류)_num'] = 2100
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축":
          value['공종(대분류)_num'] = 2200
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="산업설비":
          value['공종(대분류)_num'] = 2310
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="기계설비":
          value['공종(대분류)_num'] = 2320
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="전기설비":
          value['공종(대분류)_num'] = 2330
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="통신설비":
          value['공종(대분류)_num'] = 2340
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="기타":
          value['공종(대분류)_num'] = 2900
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="토목":
          value['공종(대분류)_num'] = 3100
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="건축":
          value['공종(대분류)_num'] = 3200
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="산업설비":
          value['공종(대분류)_num'] = 3310
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="기계설비":
          value['공종(대분류)_num'] = 3320
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="전기설비":
          value['공종(대분류)_num'] = 3330
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="통신설비":
          value['공종(대분류)_num'] = 3340
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="기타":
          value['공종(대분류)_num'] = 3900
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="토목":
          value['공종(대분류)_num'] = 4100
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="건축":
          value['공종(대분류)_num'] = 4200
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="산업설비":
          value['공종(대분류)_num'] = 4310
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="기계설비":
          value['공종(대분류)_num'] = 4320
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="전기설비":
          value['공종(대분류)_num'] = 4330
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="통신설비":
          value['공종(대분류)_num'] = 4340
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="기타":
          value['공종(대분류)_num'] = 4900
        elif value['시설물대분류']=="기타" and value ['공종(대분류)']=="기타":
          value['공종(대분류)_num'] = 9900


    for key, value in final_result.items():
        if  value['시설물대분류']=="토목" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 1101
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="강구조물공사" :
          value['공종(소분류)_num'] = 1102
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="관공사" :
          value['공종(소분류)_num'] = 1103
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="관공사 부대공사" :
          value['공종(소분류)_num'] = 1104
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="교량공사" :
          value['공종(소분류)_num'] = 1105
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="댐 및 제방공사" :
          value['공종(소분류)_num'] = 1106
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="도로 및 포장공사" :
          value['공종(소분류)_num'] = 1107
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="말뚝공사" :
          value['공종(소분류)_num'] = 1108
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="지반개량공사" :
          value['공종(소분류)_num'] = 1109
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="지반조사" :
          value['공종(소분류)_num'] = 1110
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="철근콘크리트공사" :
          value['공종(소분류)_num'] = 1111
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="철도 및 궤도공사" :
          value['공종(소분류)_num'] = 1112
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="터널공사" :
          value['공종(소분류)_num'] = 1113
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="토공사" :
          value['공종(소분류)_num'] = 1114
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="프리캐스트 콘크리트공사" :
          value['공종(소분류)_num'] = 1115
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="하천공사" :
          value['공종(소분류)_num'] = 1116
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="항만공사" :
          value['공종(소분류)_num'] = 1117
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 1118
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 1199
        elif  value['시설물대분류']=="토목" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 1201
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="건축물 부대공사" :
          value['공종(소분류)_num'] = 1203
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="금속공사" :
          value['공종(소분류)_num'] = 1204
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="도장공사" :
          value['공종(소분류)_num'] = 1205
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="철근콘크리트공사" :
          value['공종(소분류)_num'] = 1207
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="방수공사" :
          value['공종(소분류)_num'] = 1208
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="타일 및 돌공사" :
          value['공종(소분류)_num'] = 1218
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 1220
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 1299
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="산업설비" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 1311
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="산업설비" and value['공종(소분류)']=="산업설비공사" :
          value['공종(소분류)_num'] = 1312
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="산업설비" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 1318
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="산업설비" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 1319
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="기계설비" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 1321
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="기계설비" and value['공종(소분류)']=="기계설비공사" :
          value['공종(소분류)_num'] = 1322
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="기계설비" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 1328
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="기계설비" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 1329
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="전기설비" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 1331
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="전기설비" and value['공종(소분류)']=="전기설비공사" :
          value['공종(소분류)_num'] = 1332
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="전기설비" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 1338
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="전기설비" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 1339
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="통신설비" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 1341
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="통신설비" and value['공종(소분류)']=="통신설비공사" :
          value['공종(소분류)_num'] = 1342
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="통신설비" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 1348
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="통신설비" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 1349
        elif value['시설물대분류']=="토목" and value ['공종(대분류)']=="기타" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 1999
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 2101
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="강구조물공사" :
          value['공종(소분류)_num'] = 2102
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="관공사" :
          value['공종(소분류)_num'] = 2103
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="관공사 부대공사" :
          value['공종(소분류)_num'] = 2104
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="도로 및 포장공사" :
          value['공종(소분류)_num'] = 2107
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="말뚝공사" :
          value['공종(소분류)_num'] = 2108
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="지반개량공사" :
          value['공종(소분류)_num'] = 2109
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="지반조사" :
          value['공종(소분류)_num'] = 2110
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="철근콘크리트공사" :
          value['공종(소분류)_num'] = 2111
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="철도 및 궤도공사" :
          value['공종(소분류)_num'] = 2112
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="토공사" :
          value['공종(소분류)_num'] = 2114
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 2118
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 2199
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 2201
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="건축 토공사" :
          value['공종(소분류)_num'] = 2202
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="건축물 부대공사" :
          value['공종(소분류)_num'] = 2203
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="금속공사" :
          value['공종(소분류)_num'] = 2204
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="도장공사" :
          value['공종(소분류)_num'] = 2205
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="목공사" :
          value['공종(소분류)_num'] = 2206
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="미장공사" :
          value['공종(소분류)_num'] = 2207
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="방수공사" :
          value['공종(소분류)_num'] = 2208
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="수장공사" :
          value['공종(소분류)_num'] = 2209
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="조경공사" :
          value['공종(소분류)_num'] = 2210
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="조적공사" :
          value['공종(소분류)_num'] = 2211
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="지반조사" :
          value['공종(소분류)_num'] = 2212
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="지붕 및 홈통공사" :
          value['공종(소분류)_num'] = 2213
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="지정공사" :
          value['공종(소분류)_num'] = 2214
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="창호 및 유리공사" :
          value['공종(소분류)_num'] = 2215
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="철골공사" :
          value['공종(소분류)_num'] = 2216
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="철근콘크리트공사" :
          value['공종(소분류)_num'] = 2217
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="타일 및 돌공사" :
          value['공종(소분류)_num'] = 2218
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="특수 건축물공사" :
          value['공종(소분류)_num'] = 2219
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 2220
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 2299
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="산업설비" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 2311
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="산업설비" and value['공종(소분류)']=="산업설비공사" :
          value['공종(소분류)_num'] = 2312
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="산업설비" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 2318
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="산업설비" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 2319
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="기계설비" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 2321
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="기계설비" and value['공종(소분류)']=="기계설비공사" :
          value['공종(소분류)_num'] = 2322
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="기계설비" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 2328
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="기계설비" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 2329
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="전기설비" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 2331
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="전기설비" and value['공종(소분류)']=="전기설비공사" :
          value['공종(소분류)_num'] = 2332
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="전기설비" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 2338
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="전기설비" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 2339
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="통신설비" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 2341
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="통신설비" and value['공종(소분류)']=="통신설비공사" :
          value['공종(소분류)_num'] = 2342
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="통신설비" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 2348
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="통신설비" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 2349
        elif value['시설물대분류']=="건축" and value ['공종(대분류)']=="기타" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 2999
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 3101
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="관공사" :
          value['공종(소분류)_num'] = 3103
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="관공사 부대공사" :
          value['공종(소분류)_num'] = 3104
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="도로 및 포장공사" :
          value['공종(소분류)_num'] = 3107
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="말뚝공사" :
          value['공종(소분류)_num'] = 3108
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="지반개량공사" :
          value['공종(소분류)_num'] = 3109
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="철근콘크리트공사" :
          value['공종(소분류)_num'] = 3111
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="터널공사" :
          value['공종(소분류)_num'] = 3113
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="토공사" :
          value['공종(소분류)_num'] = 3114
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="항만공사" :
          value['공종(소분류)_num'] = 3117
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 3118
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 3199
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 3201
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="건축 토공사" :
          value['공종(소분류)_num'] = 3202
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="건축물 부대공사" :
          value['공종(소분류)_num'] = 3203
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="금속공사" :
          value['공종(소분류)_num'] = 3204
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="도장공사" :
          value['공종(소분류)_num'] = 3205
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="목공사" :
          value['공종(소분류)_num'] = 3206
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="미장공사" :
          value['공종(소분류)_num'] = 3207
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="방수공사" :
          value['공종(소분류)_num'] = 3208
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="수장공사" :
          value['공종(소분류)_num'] = 3209
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="조적공사" :
          value['공종(소분류)_num'] = 3211
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="지붕 및 홈통공사" :
          value['공종(소분류)_num'] = 3213
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="철골공사" :
          value['공종(소분류)_num'] = 3216
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="철근콘크리트공사" :
          value['공종(소분류)_num'] = 3217
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 3220
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 3299
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="산업설비" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 3311
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="산업설비" and value['공종(소분류)']=="산업설비공사" :
          value['공종(소분류)_num'] = 3312
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="산업설비" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 3318
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="산업설비" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 3319
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="기계설비" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 3321
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="기계설비" and value['공종(소분류)']=="기계설비공사" :
          value['공종(소분류)_num'] = 3322
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="기계설비" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 3328
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="기계설비" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 3329
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="전기설비" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 3331
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="전기설비" and value['공종(소분류)']=="전기설비공사" :
          value['공종(소분류)_num'] = 3332
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="전기설비" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 3338
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="전기설비" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 3339
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="통신설비" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 3341
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="통신설비" and value['공종(소분류)']=="통신설비공사" :
          value['공종(소분류)_num'] = 3342
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="통신설비" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 3348
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="통신설비" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 3349
        elif value['시설물대분류']=="산업환경설비" and value ['공종(대분류)']=="기타" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 3999
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 4101
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="강구조물공사" :
          value['공종(소분류)_num'] = 4102
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="관공사" :
          value['공종(소분류)_num'] = 4103
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="관공사 부대공사" :
          value['공종(소분류)_num'] = 4104
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="도로 및 포장공사" :
          value['공종(소분류)_num'] = 4107
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="철근콘크리트공사" :
          value['공종(소분류)_num'] = 4111
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="터널공사" :
          value['공종(소분류)_num'] = 4113
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="토공사" :
          value['공종(소분류)_num'] = 4114
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="하천공사" :
          value['공종(소분류)_num'] = 4116
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 4118
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="토목" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 4199
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="건축 토공사" :
          value['공종(소분류)_num'] = 4202
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="조경공사" :
          value['공종(소분류)_num'] = 4210
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="철골공사" :
          value['공종(소분류)_num'] = 4216
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="철근콘크리트공사" :
          value['공종(소분류)_num'] = 4217
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 4218
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="건축" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 4299
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="산업설비" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 4311
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="산업설비" and value['공종(소분류)']=="산업설비공사" :
          value['공종(소분류)_num'] = 4312
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="산업설비" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 4318
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="산업설비" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 4319
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="기계설비" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 4321
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="기계설비" and value['공종(소분류)']=="기계설비공사" :
          value['공종(소분류)_num'] = 4322
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="기계설비" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 4328
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="기계설비" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 4329
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="전기설비" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 4331
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="전기설비" and value['공종(소분류)']=="전기설비공사" :
          value['공종(소분류)_num'] = 4332
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="전기설비" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 4338
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="전기설비" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 4339
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="통신설비" and value['공종(소분류)']=="가설공사" :
          value['공종(소분류)_num'] = 4341
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="통신설비" and value['공종(소분류)']=="통신설비공사" :
          value['공종(소분류)_num'] = 4342
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="통신설비" and value['공종(소분류)']=="해체 및 철거공사" :
          value['공종(소분류)_num'] = 4348
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="통신설비" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 4349
        elif value['시설물대분류']=="조경" and value ['공종(대분류)']=="기타" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 4999
        elif value['시설물대분류']=="기타" and value ['공종(대분류)']=="기타" and value['공종(소분류)']=="기타" :
          value['공종(소분류)_num'] = 9999


    return  final_result